### ISSUE TITLE
Adapter not working with latest jscontroller (6.0.11)

### ISSUE THREAD

**Issue by Cumulus7** [t4qjXH8N/ioBroker.wiffi-wz#185]
Hi,

the adapter unfortunately stopped working after i updated to js-controller 6.0.11

Here are the error-messages:

instance system.adapter.wiffi-wz.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
- caught by controller[0]: Node.js v20.18.0
- caught by controller[0]: at node:internal/main/run_main_module:28:49
- caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
- caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:1104:12)
- caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1288:32)
- caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
- caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1469:14)
- caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.wiffi-wz/main.js:675:5)
- caught by controller[0]: at startAdapter (/opt/iobroker/node_modules/iobroker.wiffi-wz/main.js:42:15)
- caught by controller[0]: TypeError: utils.Adapter is not a constructor
- caught by controller[0]: ^
- caught by controller[0]: adapter = new utils.Adapter(options);
- Caught by controller[0]: /opt/iobroker/node_modules/iobroker.wiffi-wz/main.js:42

THX for any help,
Markus

**Comment by Cumulus7** [comment]
Hi, 
update: the adapter suddenly started working again. I did nothing... but it works now.

I will close this issue!
